networks:
  custom:
    ipam:
      config:
        - subnet: 10.5.0.0/16
services:
  postgres-db:
    image: ankane/pgvector:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      custom:
  redis-db:
    image: redis
    networks:
      custom:
  identity-svc:
    image: duynguyenbui/identity-svc:latest
    pull_policy: missing
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Database=Host=postgres-db;Port=5432;Database=IdentityDB;Username=postgres;Password=postgrespw
      - WebAppClient=http://app.ehealthscape.com
      - VIRTUAL_HOST=id.ehealthscape.com
    networks:
      custom:
        ipv4_address: 10.5.0.200
    restart: unless-stopped
  healthrc-svc-1:
    image: duynguyenbui/healthrc-svc:latest
    pull_policy: missing
    environment:
      - ConnectionStrings__Database=Host=postgres-db;Port=5432;Database=HealthRecordDB;Username=postgres;Password=postgrespw
      - ConnectionStrings__Redis=redis-db:6379
      - QueueName=speeches_1
      - Identity__Url=http://identity-svc
      - Identity__Audience=identity-svc/resources
      - Identity__Scopes__healthrecords="HealthRecord API"
    depends_on:
      - postgres-db
      - redis-db
    networks:
      custom:
  healthrc-svc-2:
    image: duynguyenbui/healthrc-svc:latest
    pull_policy: missing
    environment:
      - ConnectionStrings__Database=Host=postgres-db;Port=5432;Database=HealthRecordDB;Username=postgres;Password=postgrespw
      - ConnectionStrings__Redis=redis-db:6379
      - QueueName=speeches_2
      - Identity__Url=http://identity-svc
      - Identity__Audience=identity-svc/resources
      - Identity__Scopes__healthrecords="HealthRecord API"
    depends_on:
      - postgres-db
      - redis-db
    networks:
      custom:
  speech-svc:
    image: duynguyenbui/speech-svc:latest
    pull_policy: missing
    environment:
      - ConnectionStrings__Redis=redis-db:6379
      - Prefix=speeches_
      - NumberOfConsumers=2
      - Identity__Url=http://identity-svc
      - Identity__Audience=identity-svc/resources
      - Identity__Scopes__speech="Speech Recognition API"
    depends_on:
      - redis-db
    networks:
      custom:
  bff-svc:
    image: duynguyenbui/bff-svc:latest
    pull_policy: missing
    environment:
      - ReverseProxy__Clusters__healthrecords__LoadBalancingPolicy=RoundRobin
      - ReverseProxy__Clusters__healthrecords__Destinations__destination1__Address=http://healthrc-svc-1:8080
      - ReverseProxy__Clusters__healthrecords__Destinations__destination2__Address=http://healthrc-svc-2:8080
      - ReverseProxy__Clusters__speech__Destinations__speechApi__Address=http://speech-svc:8080
      - ASPNETCORE_URLS=http://+:80
      - VIRTUAL_HOST=api.ehealthscape.com
    networks:
      custom:
  web-app:
    image: duynguyenbui/web-app:latest
    pull_policy: missing
    volumes:
      - /var/lib/web/data
    extra_hosts:
      - id.ehealthscape.com:10.5.0.200
    environment:
      - NEXTAUTH_SECRET=ra9YcqAz13Out0Mw3jVtQvMcL0EgOEIyCYKtYnwWONg=
      - NEXTAUTH_URL=http://app.ehealthscape.com
      - NEXTAUTH_URL_INTERNAL=http://web-app:3000
      - DUENDE_IDS6_ID=webapp
      - DUENDE_IDS6_SECRET=secret
      - DUENDE_IDS6_ISSUER=http://id.ehealthscape.com
      - HEALTH_RECORD_API_URL=http://bff-svc/healthrc
      - HEALTH_RECORD_API_VERSION=1.0
      - SPEECH_RECOGNITION_API_URL=http://bff-svc/speech
      - SPEECH_RECOGNITION_API_VERSION=1.0
      - VIRTUAL_HOST=app.ehealthscape.com
      - VIRTUAL_PORT=3000
    networks:
      custom:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./src/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      custom:
  grafana:
    image: grafana/grafana
    user: "472"
    depends_on:
      - prometheus
    volumes:
      - ./src/grafana/config:/etc/grafana
      - ./src/grafana/dashboards/:/var/lib/grafana/dashboards
    environment:
      - GF_SERVER_HTTP_PORT=2345
      - VIRTUAL_HOST=monitor.ehealthscape.com
      - VIRTUAL_PORT=2345
    networks:
      custom:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      custom:
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
volumes:
  postgres-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/buiduynguyen/Desktop/postgres-data