services:
  postgres.db:
    image: ankane/pgvector:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
  redis.db:
    image: redis
    ports:
      - "6379:6379"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./src/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    user: "472"
    depends_on:
      - prometheus
    volumes:
      - ./src/grafana/config:/etc/grafana
      - ./src/grafana/dashboards/:/var/lib/grafana/dashboards
    ports:
      - "4444:3000"