version: '3.4'

services:
#  health-record.api:
#    image: healthrecord.api
#    build:
#      context: .
#      dockerfile: src/HealthRecord.API/Dockerfile
#  speech-recognition.api:
#    image: speechrecognition.api
#    build:
#      context: .
#      dockerfile: src/SpeechRecognition.API/Dockerfile
  postgres.db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw