version: '3'

tasks:
  # Kubernetes
  create-namespace:
    cmds:
      - kubectl create namespace ehealthscape
    desc: "Create the ehealthscape namespace"
  
  install-services:
    cmds:
      - helm upgrade --install postgres ./k8s/charts/postgres/ --namespace ehealthscape
      - helm upgrade --install redis ./k8s/charts/redis/ --namespace ehealthscape
      - helm upgrade --install speech ./k8s/charts/speech/ --namespace ehealthscape
      - helm upgrade --install healthrc ./k8s/charts/healthrc/ --namespace ehealthscape
      - helm upgrade --install bff ./k8s/charts/bff/ --namespace ehealthscape
    desc: "Install the main services using Helm"
  
  create-tls-secret:
    cmds:
      - kubectl create secret tls ehealthscape-app-tls --key ./k8s/certs/server.key --cert ./k8s/certs/server.crt --namespace ehealthscape
    desc: "Create TLS secret for the application"
  
  install-ingress:
    cmds:
      - kubectl apply -f ./k8s/charts/nginx/deploy.yaml
    desc: "Upgrade and install ingress-nginx"

  apply-ingress:
    cmds:
      - kubectl apply -f ./k8s/charts/nginx/ingress.yaml --namespace ehealthscape
    desc: "Apply the ingress configuration"

  run-k8s:
    deps:
      - create-namespace
      - create-tls-secret
      - install-services
      - install-ingress
      - apply-ingress
    desc: "Run all tasks in sequence"
  
  release-resources:
    cmds:
      - kubectl delete all --all --namespace ehealthscape
      - kubectl delete -f ./k8s/charts/nginx/deploy.yaml
      - kubectl delete namespace ehealthscape
      - kubectl delete namespace ingress-nginx
    desc: "Release all resources in the ehealthscape and ingress-nginx namespaces"
  