import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { getServerSession } from "next-auth";
import authOptions from "@/auth-options";
import { Provider } from "@/components/providers/session-provider";
import { Toaster } from "sonner";
import { ModalProvider } from "@/components/providers/modal-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Health Record WebApp",
  description: "Generated by Duy Nguyen BUI",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Provider session={session}>
            <div className="flex flex-col justify-between w-full h-full min-h-screen">
              <Header />
              <main className="flex-auto w-full max-w-7xl px-4 py-4 mx-auto sm:px-6 md:py-6">
                {children}
              </main>
            </div>
            <ModalProvider />
            <Toaster />
          </Provider>
        </ThemeProvider>
      </body>
    </html>
  );
}
