global:
  scrape_interval: 1s # makes for a good demo

scrape_configs:
  - job_name: 'healthrecords'
    static_configs:
      - targets: ['host.docker.internal:5002']
  - job_name: 'identity-server'
    static_configs:
      - targets: ['host.docker.internal:5001']