global:
  scrape_interval: 1s # makes for a good demo

scrape_configs:
  - job_name: 'speech-svc'
    static_configs:
      - targets: [ 'speech-svc:8080' ]

  - job_name: 'healthrc-svc-1'
    static_configs:
      - targets: [ 'healthrc-svc-1:8080' ]
        
  - job_name: 'healthrc-svc-2'
    static_configs:
      - targets: [ 'healthrc-svc-2:8080' ]
        
  - job_name: 'bff-svc'
    static_configs:
      - targets: [ 'bff-svc' ]
        
  - job_name: 'identity-svc'
    static_configs:
      - targets: [ 'identity-svc' ]