name: mobile-bff-svc.yml
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/Mobile.Bff/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Docker
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}"
          file: src/Mobile.Bff/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mobile-bff-svc:latest